name: continuous build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO Add windows test by using "windows-latest"
        os: [ubuntu-latest, macos-latest]
        python-version: [ '3.6', '3.7', '3.8']
        exclude:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Other Dependencies
        run: |
          conda env update --prune -p conda/cpu/py3 -f env/cpu/py3.yml

      - name: Run Unittests
        run: |
          pytest -n 4 -m 'not (gpu or serial)' --durations=30 --cov=./ --cov-report=xml tests/unittest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          env_vars: OS,PYTHON
