name: continuous build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO Add windows test by using "windows-latest"
        os: [ubuntu-latest]
        python-version: [ '3.6', '3.7', '3.8']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compilation cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          # We include the commit sha in the cache key, as new cache entries are
          # only created if there is no existing entry for the key yet.
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          # Restore any ccache cache entry, if none for
          # ${{ runner.os }}-ccache-${{ github.sha }} exists
          restore-keys: |
            ${{ runner.os }}-ccache

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Sanity Check
        shell: bash -l {0}
        run: |
          source ci/prepare_clean_env.sh cpu/py3
          make lintdir=src/gluonnlp lint

      - name: Unittest
        shell: bash -l {0}
        run: |
          source ci/prepare_clean_env.sh cpu/py3
          pytest -n 4 -m 'not (gpu or serial)' --durations=30 --cov=./ --cov-report=xml tests/unittest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          env_vars: OS,PYTHON
